apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: tamboot-cloud-admin-system-ms
  name: tamboot-cloud-admin-system-ms
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tamboot-cloud-admin-system-ms
  template:
    metadata:
      labels:
        app: tamboot-cloud-admin-system-ms
        buildVersion: build-${BUILD_ID}
    spec:
      containers:
      - command:
        - java
        - '-Xms64m'
        - '-Xmx512m'
        - '-jar'
        - app.jar
        env:
        - name: LANG
          value: C.UTF-8
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-1.8-openjdk
        image: >-
          registry-vpc.cn-shenzhen.aliyuncs.com/registry_tam/tamboot-cloud-admin-system-ms:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        name: tamboot-cloud-admin-system-ms
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: volume-tmp
        - mountPath: /usr/local/app/config
          name: volume-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 20
      volumes:
      - emptyDir: {}
        name: volume-tmp
      - configMap:
          defaultMode: 420
          name: tamboot-cloud-admin-system-ms-config
        name: volume-config