apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: tamboot-cloud-admin-system-app
    environment: product
    tier: backend
  name: tamboot-cloud-admin-system-app
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tamboot-cloud-admin-system-app
  template:
    metadata:
      labels:
        app: tamboot-cloud-admin-system-app
    spec:
      containers:
      - command:
        - java
        - '-Xms64m'
        - '-Xmx256m'
        - '-jar'
        - app.jar
        env:
        - name: LANG
          value: C.UTF-8
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-1.8-openjdk
        image: >-
          registry-vpc.cn-shenzhen.aliyuncs.com/registry_tam/tamboot-cloud-admin-system-app:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        name: tamboot-cloud-admin-system-app
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: volume-tmp
        - mountPath: /usr/local/app/config
          name: volume-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: volume-tmp
      - configMap:
          defaultMode: 420
          name: tamboot-cloud-admin-system-app-config
        name: volume-config

---
apiVersion: v1
kind: Service
metadata:
  name: tamboot-cloud-admin-system-app-service
  namespace: backend
spec:
  ports:
  - name: tamboot-cloud-admin-system-app-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tamboot-cloud-admin-system-app
  sessionAffinity: None
  type: ClusterIP